import '@styles/tailwind.css';
import { Inter } from 'next/font/google';
import { ProviderAuth } from '@hooks/useAuth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Boilerplate',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <ProviderAuth>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ProviderAuth>
    </>
    // <html lang="en">
    //   <body className={inter.className}>
    //     <MainLayout>{children}</MainLayout>
    //   </body>
    // </html>
  );
}
