import '@styles/tailwind.css';
import { Inter } from 'next/font/google';
import MainLayout from '@layout/MainLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Boilerplate',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    // <html lang="en">
    //   <body className={inter.className}>
    //     <MainLayout>{children}</MainLayout>
    //   </body>
    // </html>
  );
}
