import '@styles/tailwind.css';
import { Inter } from 'next/font/google';
import MainLayout from '@layout/MainLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Boilerplate',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }) {
  return <MainLayout>{children}</MainLayout>;
}
